version: "3.8"

services:
  corner-bet:
    image: ghcr.io/lsk-tech/corner-bot-service:${IMAGE_TAG}
    environment:
      - CORNER_BET_USERNAME=${CORNER_BET_USERNAME}
      - CORNER_BET_PASSWORD=${CORNER_BET_PASSWORD}
      - GAME_COMPACT_API_URL=${GAME_COMPACT_API_URL}
      - GAME_COMPACT_API_TOKEN=${GAME_COMPACT_API_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - TZ=${TZ}
    shm_size: "2gb"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mansao-green-prod-net
      - appapi-prod-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  mansao-green-prod-net:
    external: true
    name: mansao-green-prod_web-net
  appapi-prod-net:
    external: true
    name: appapi_appapi-prod-net