version: "3.8"
services:
  corner-bet:
    image: ghcr.io/lsk-tech/corner-bot-service:${IMAGE_TAG}
    environment:
      - CORNER_BET_USERNAME=${CORNER_BET_USERNAME}
      - CORNER_BET_PASSWORD=${CORNER_BET_PASSWORD}
      - GAME_COMPACT_API_URL=${GAME_COMPACT_API_URL}
      - GAME_COMPACT_API_TOKEN=${GAME_COMPACT_API_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - TZ=${TZ}
    shm_size: "2gb"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mansao-green-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first

networks:
  mansao-green-net:
    external: true
    name: ${NETWORK_NAME}